name: Full Build

description: Builds, tests, and creates binaries that are ready for release.

inputs:
  version:
    description: 'Version number for the app'
    default: '0.0.0'
  archs:
    description: 'Architectures for the build'
    default: 'x64 arm64'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-dotnet@v4

    - name: Build
      shell: bash
      run: dotnet build

    - name: Test
      shell: bash
      run: dotnet test

    - name: Create Binaries
      shell: bash
      run: |
        for arch in ${{ inputs.archs }}; do
          dotnet publish ./RadialActions/RadialActions.csproj -o "publish/$arch" -c Release -f net10.0-windows --os win --arch $arch --self-contained -p:PublishSingleFile=true -p:DebugType=embedded -p:Version=${{ inputs.version }}
        done

    - name: Create Portable ZIPs
      shell: pwsh
      run: |
        $archs = "${{ inputs.archs }}".Split(" ")
        foreach ($arch in $archs) {
          Compress-Archive -Path "publish/$arch/*" -DestinationPath "publish/RadialActions-${{ inputs.version }}-$arch.zip"
        }

    - name: Create MSI Installers
      shell: bash
      run: |
        dotnet tool install --global wix --version 6.0.*
        for arch in ${{ inputs.archs }}; do
          wix build Product.wxs -arch $arch -d Version=${{ inputs.version }} -d Arch=$arch -o "publish/RadialActions-${{ inputs.version }}-$arch.msi"
        done

    - uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        path: |
          publish/*.zip
          publish/*.msi
